#!/bin/bash
if [[ $UID != 0 ]] ; then
  echo "This script requires sudo privileges to access hardware info"
  echo "If you do not have such privaleges, comment out 'sudo dmidecode...'"
  exit 1
fi

echo " -- Storage -------------"
echo "Device         Total  Used  Free  Pct  MntPoint"
df -h | grep "dev/sd"
df -h | grep "/mnt"

echo ""
lsblk -o KNAME,SIZE,MODEL

echo -e "\n -- Memory ---------------"
echo "             total       used       free     shared    buffers     cached"
free -m | grep "Mem"

echo ""
sudo dmidecode --type 17 | sed -n 'H; /^Memory/h; ${g;p;}'
