#!/bin/bash
#
# Adjust system backlight

sysfs="/sys/class/backlight/intel_backlight"
max=`cat ${sysfs}/max_brightness`
level=`cat ${sysfs}/brightness`

set_brightness() {
level=$1

if [ $level -lt 1 ] ; then
 level=1
elif [ $level -gt $max ] ; then
  level=$max
fi

echo $level > $sysfs/brightness
}

if [[ ! $1 =~ ^[[:digit:]]+$ ]]; then
  echo "usage: blt <integer>"
else
  set_brightness $@
fi
